#!/bin/bash

dist=`awk '{print $1 " " $2}' /etc/issue`

declare -x FRAME
declare -x FRAME_INTERVAL

function icon() {
      FRAME=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
      FRAME_INTERVAL=0.1
	  local step=0

	  while [ "$step" -lt "${#CMDS[@]}" ]; do
		${CMDS[$step]} & pid=$!

		while ps -p $pid &>/dev/null; do
		  echo -ne "\\r[   ] ${STEPS[$step]} ..."

		  for k in "${!FRAME[@]}"; do
		    echo -ne "\\r[ ${FRAME[k]} ]"
		    sleep $FRAME_INTERVAL
		  done
		done

		echo -ne "\\r[ ✔ ] ${STEPS[$step]}\\n"
		step=$((step + 1))
	  done

}
tput setaf 3
STEPS='Checking youre system'
CMDS='sleep 2'
icon
echo ""
hostnamectl
echo ""

#setup llama3
STEPS='Ollama status checking...'
CMDS='sleep 2'
icon
if [[ -f /usr/local/bin/ollama ]]; then
    echo "Ollama is already installed in $dist"
	ollama pull llama3:8b
else
	curl -fsSL https://ollama.com/install.sh | sh
	ollama pull llama3:8b
fi

STEPS='Installing Dependencies'
CMDS='sleep 2'
icon
#install dependencies for python
sudo apt-get install python3 python3-dev python3-pip portaudio19-dev -y

STEPS='Set python3 as default'
CMDS='sleep 2'
icon
#install dependencies for python
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old

STEPS='instaling python dependencies'
CMDS='sleep 2'
icon
pip3 install pyaudio
pip3 install SpeechRecognition
pip3 install gTTS
pip3 install chime
pip install llama3-package
pip install playsound


STEPS='Creating scripts'
CMDS='sleep 2'
icon
touch ~/inem.py

STEPS='Generating Code'
CMDS='sleep 2'
icon
cat <<EOF>> ~/inem.py
#!/usr/bin/python

import speech_recognition as src
from gtts import gTTS
from playsound import playsound
import chime
import requests
from llama3 import Llama3Model
import webbrowser
import os
import urllib.request
import re


model = Llama3Model()
chime.theme('zelda')

#os.system("python a.py")

def intro():
    teks = ('Halo nama saya inem, katakan sesuatu setelah bunyi beep')
    bahasa = 'id'
    def speak():
        suara = gTTS(text=teks,lang=bahasa, slow=False)
        suara.save('sound.mp3')
        playsound('sound.mp3')
    speak()
    wakeword()
    
def wakeword():
    mendengar = src.Recognizer()
    with src.Microphone() as source:
        chime.info()
        print('+ Menunggu wakeword ...')
        suara = mendengar.listen(source,phrase_time_limit=2)
        try:
            dengar = mendengar.recognize_google(suara,language='id-ID')
            dengar = str(dengar).lower()
            print('+ Wakeword Diterima...')
            print('+ You: ', dengar)
            
            if('inem' in dengar):
                teks = ('Ya tuan, apa yang bisa saya bantu, silahkan katakan sesuatu setelah bunyi beep')
                bahasa = 'id'
                def speak():
                    suara = gTTS(text=teks,lang=bahasa, slow=False)
                    suara.save('sound.mp3')
                    playsound('sound.mp3')
                speak()
                chat()
            else:
                teks = ('maaf saya tidak mengerti maksud anda, silahkan anda ulangi kembali seteah bunyi beep')
                bahasa = 'id'
                def speak():
                    suara = gTTS(text=teks,lang=bahasa, slow=False)
                    suara.save('sound.mp3')
                    playsound('sound.mp3')
                speak()
                wakeword()
        except:
            pass
            wakeword()
            
def chat():
    chime.info()
    mendengar = src.Recognizer()
    with src.Microphone() as source:
        chime.info()
        print('+ Menunggu Perintah ...')
        suara = mendengar.listen(source,phrase_time_limit=5)
        try:
            dengar = mendengar.recognize_google(suara,language='id-ID')
            dengar = str(dengar).lower()
            print('+ Perintah Diterima...')
            print('+ You: ', dengar)

            if("buka youtube" in dengar ):             
                youtube()
            if('buka terminal'in dengar):
                terminal()
            if('buka browser'in dengar):
               browser()

            response = model.prompt(dengar)
            print("+ Inem:", response)
            teks = (response)
            bahasa = 'id'
            def speak():
                suara = gTTS(text=teks,lang=bahasa, slow=False)
                suara.save('sound.mp3')
                playsound('sound.mp3')
            speak()
            wakeword()
        except:
            pass
            wakeword()


def youtube():
    teks = ("Ucapkan kata kunci pencarian setelah bunyi beep")
    bahasa = 'id'
    def speak():
        suara = gTTS(text=teks,lang=bahasa, slow=False)
        suara.save('sound.mp3')
        playsound('sound.mp3')
    speak()
    chime.info()

    mendengar = src.Recognizer()
    with src.Microphone() as source:
         print('+ Menunggu Kata kunci pencarian ...')
         suara = mendengar.listen(source,phrase_time_limit=5)
         try:
          dengar = mendengar.recognize_google(suara,language='id-ID')
          dengar = str(dengar).lower()
          print('+ Kata kunci pencarian diterima...')           
          print('+ You: ', dengar)

          keyword=(dengar)
          webbrowser.open("https://www.youtube.com/results?search_query="+keyword,new=2)

          teks = ("Membuka youtube dengan kata kunci" + dengar)
          bahasa = 'id'
          def speak():
              suara = gTTS(text=teks,lang=bahasa, slow=False)
              suara.save('sound.mp3')
              playsound('sound.mp3')
          speak()
          wakeword()
         except:
            pass
            wakeword()


def terminal():
    teks = ("Membuka gnome-terminal")
    bahasa = 'id'
    def speak():
        suara = gTTS(text=teks,lang=bahasa, slow=False)
        suara.save('sound.mp3')
        playsound('sound.mp3')
    speak()
    os.system("gnome-terminal")
    wakeword()
    
def browser():
    teks = ("Ucapkan kata kunci pencarian setelah bunyi beep")
    bahasa = 'id'
    def speak():
        suara = gTTS(text=teks,lang=bahasa, slow=False)
        suara.save('sound.mp3')
        playsound('sound.mp3')
    speak()
    chime.info()

    mendengar = src.Recognizer()
    with src.Microphone() as source:
         print('+ Menunggu Kata kunci pencarian ...')
         suara = mendengar.listen(source,phrase_time_limit=5)
         try:
          dengar = mendengar.recognize_google(suara,language='id-ID')
          dengar = str(dengar).lower()
          print('+ Kata kunci pencarian diterima...')           
          print('+ You: ', dengar)

          keyword=(dengar)
          webbrowser.open("https://www.google.com/search?q="+keyword,new=2)

          teks = ("Membuka browser dengan kata kunci" + dengar)
          bahasa = 'id'
          def speak():
              suara = gTTS(text=teks,lang=bahasa, slow=False)
              suara.save('sound.mp3')
              playsound('sound.mp3')
          speak()
          wakeword()
         except:
            pass
            wakeword()
intro()

EOF

STEPS='Creating executeable scripts'
CMDS='sleep 2'
icon
touch ~/inem

cat << EOF >> ~/inem
#!/usr/bin/bash
python /usr/bin/inem.py
EOF

chmod +x ~/inem
chmod +x ~/inem.py

sudo mv ~/inem /usr/bin/inem
sudo mv ~/inem.py /usr/bin/inem.py

STEPS='How to use !'
CMDS='sleep 2'
icon
echo "============================================ How To ======================================================="
echo "Saat [+ Menunggu wakeword..] muncul sebutkan kata kunci [Inem] kemudian setelah muncul [+ Menunggu Perintah ...] sampaikanlah pertanyaan yang ingin anda tanyakan"
echo ""
echo "Pemrosesan jawban tergantung pada spesifikasi komputer anda, apabila specs komputer anda mempergunakan GPU maka pemrosesan jawaban akan lebih cepat jika tidak maka system akan mempergunakan CPU"
echo ""
echo "Untuk berikutnya anda dapat mengetikkan [inem] pada terminal anda untuk mengeksekusi perintah selanjutnya"
echo "==========================================================================================================="
echo ""
sleep 5

STEPS='Running the scripts'
CMDS='sleep 2'
icon
inem

tput sgr0
